name = "login-page"
main = "src/worker.js"
compatibility_date = "2024-11-01"

[vars]
EMAIL_FROM = "onboarding@resend.dev"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "login_page_db"
database_id ="0d6d1f02-f13b-4154-bcbc-d0ae7baf4d05"
